languageCode = "en-us"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "" # your analitics ID

enableGitInfo = false
pygmentsCodeFences = true
baseurl = "https://avatarDataset.github.io"

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

[[Params.listeLangues]]
code = "en"

[Languages]

[Languages.en]
weight = 2
languageCode = "en-us"
title = ""
dateFormat = "January 2, 2006"
home = "Home"
logo = ""
menufixed = false

footerDescription = "Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerAboutTitle = "About"

footerLocationDescription = ""
footerLocationTitle = ""


# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
enable  = true
heading = "AvaDa: Avatar Dataset"
description = "Real large-scale dataset of human torsos captured on smartphone and external high-quality sensors"
button  = true
btnText = "Download"
btnURL  = "download"

# About 2 Section
[Languages.en.params.aboutSm]
enable  = true
title   = "Fill the gap in realistic avatar rendering and 3D reconstruction"
description = "Our dataset provides smartphone data (video and IMU) precisely synchronized with depth captured on Azure Kinect sensor as source of ground truth information for tasks of 3D reconstruction, rendering and single-shot depth estimation. Recordings were performed with blinking flash for possible usage in re-lightning tasks. Within the dataset, we deliver high-quality trajectories of the smartphone and segmentation masks for human avatars."

# Contact Section
[Languages.en.params.contact]
enable  = true
topTitle= "Request data"
title   = "Contact Us"
subtitle= "Or not"
mapLatitude = "-84.260945"
mapLongitude= "45.145059"
mapMarker   = "images/marker.png"

# Call to Action Section on About Page
[Languages.en.params.cta]
enable  = true
bg      = "images/call-to-action/call-to-action-bg-2.jpg"
title   = "Let's Create Something Together"
subtitle= "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
btnText = "Contact Us"

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "hardware"
url     = "hardware"
weight  = 2
[[menu.nav]]
name    = "dataset"
url     = "dataset"
weight  = 3
[[menu.nav]]
name    = "about"
url     = "about"
weight  = 4
[[menu.nav]]
name    = "download"
url     = "download"
weight  = 5

